import {
  MdUndo,
  MdRedo,
  MdContentCopy,
  MdDelete,
  MdFormatColorFill,
  MdMoveToInbox,
  MdTextFields,
  MdGesture,
  MdBrush,
  MdColorLens,
  MdDownload,
  MdEdit,
  MdSearch,
  MdOutlineFormatSize,
  MdLayers,
  MdFileDownload,
} from "react-icons/md";

export const activityInstructions = [
  {
    activity: "Draw Pencil/Pen",
    icon: <MdBrush />,
    details: [
      "Use the pencil for freehand sketching.",
      "The pen tool allows smoother, controlled strokes.",
    ],
  },
  {
    activity: "Shapes",
    icon: <MdGesture />,
    details: [
      "Draw rectangles, circles, and other shapes.",
      "Use the fill option to color inside shapes.",
    ],
  },
  {
    activity: "Move Shapes",
    icon: <MdMoveToInbox />,
    details: [
      "Drag shapes to reposition them.",
      "Right-click for additional options like bring to front or send to back.",
    ],
  },
  {
    activity: "Change Color",
    icon: <MdFormatColorFill />,
    details: [
      "Click the shape to change its color.",
      "Use the background color tool to set a canvas background.",
    ],
  },
  {
    activity: "Copy & Paste",
    icon: <MdContentCopy />,
    details: [
      "Press Ctrl + C to copy a shape.",
      "Press Ctrl + V to paste the copied shape beside the original.",
    ],
  },
  {
    activity: "Undo/Redo",
    icon: <MdUndo />,
    details: [
      "Press Ctrl + Z to undo the last action.",
      "Press Ctrl + Y to redo the last undone action.",
    ],
  },
  {
    activity: "Delete",
    icon: <MdDelete />,
    details: [
      "Press Delete to remove the selected shape.",
      "Click the 'Clear' button to remove all shapes on the canvas.",
    ],
  },
  {
    activity: "Text",
    icon: <MdTextFields />,
    details: [
      "Click to add text anywhere on the canvas.",
      "Right-click to change font size and color.",
    ],
  },
  {
    activity: "Download/Save",
    icon: <MdDownload />,
    details: [
      "Save your drawing to your account.",
      "Download your work as an image file.",
    ],
  },
  {
    activity: "Search & Filter Drawings",
    icon: <MdSearch />,
    details: [
      "Search drawings based on user.",
      "Filter drawings by type, date, or creator.",
    ],
  },
  {
    activity: "Edit Drawings",
    icon: <MdEdit />,
    details: [
      "Modify existing drawings easily.",
      "Use selection tools to adjust properties of a shape.",
    ],
  },
  {
    activity: "Context Menu",
    icon: <MdOutlineFormatSize />,
    details: [
      "Right-click a text to change font size.",
      "Right-click a shape to adjust color or layer positioning.",
    ],
  },
  {
    activity: "Layering",
    icon: <MdLayers />,
    details: [
      "Move shapes forward or backward in the layer stack.",
      "Use right-click options for fine control.",
    ],
  },
  {
    activity: "File Download",
    icon: <MdFileDownload />,
    details: [
      "Save your drawing as PNG or JPG.",
      "Option to keep high-quality resolution.",
    ],
  },
];

export const words = [
  "React",
  "Node",
  "MongoDB",
  "Canvas",
  "Drawing",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Kotlin",
  "Swift",
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "Vue",
  "Angular",
  "Django",
  "Flask",
  "Express",
  "GraphQL",
  "REST",
  "API",
  "Database",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Docker",
  "Kubernetes",
  "Git",
  "GitHub",
  "Algorithm",
  "Data",
  "Structure",
  "Function",
  "Variable",
  "Loop",
  "Condition",
  "Object",
  "Class",
  "Interface",
  "Inheritance",
  "Polymorphism",
  "Encapsulation",
  "Abstraction",
  "Framework",
  "Library",
  "Component",
  "State",
  "Props",
  "Hooks",
  "Context",
  "Reducer",
  "Middleware",
  "Authentication",
  "Authorization",
  "Encryption",
  "Decryption",
  "Debugging",
  "Testing",
  "Deployment",
  "Server",
  "Client",
  "Frontend",
  "Backend",
  "Fullstack",
  "DevOps",
  "Agile",
  "Scrum",
  "Sprint",
  "Repository",
  "Merge",
  "Conflict",
  "Branch",
  "Commit",
  "Push",
  "Pull",
  "Fetch",
  "Rebase",
  "Pipeline",
  "Continuous",
  "Integration",
  "Delivery",
  "Monitoring",
  "Logging",
  "Analytics",
  "Machine",
  "Learning",
  "Artificial",
  "Intelligence",
  "Neural",
  "Network",
  "Deep",
  "Learning",
  "Natural",
  "Language",
  "Processing",
  "Computer",
  "Vision",
  "Blockchain",
  "Cryptocurrency",
  "Bitcoin",
  "Ethereum",
  "Smart",
  "Contract",
  "Decentralized",
  "Application",
  "Token",
  "Wallet",
  "Exchange",
  "Cloud",
  "AWS",
  "Azure",
  "Google",
  "Firebase",
  "Heroku",
  "Netlify",
  "Vercel",
  "Domain",
  "Hosting",
  "SSL",
  "Certificate",
  "Security",
  "Firewall",
  "VPN",
  "Proxy",
  "Load",
  "Balancer",
  "Scalability",
  "Performance",
  "Optimization",
  "Latency",
  "Throughput",
  "Bandwidth",
  "Cache",
  "CDN",
  "Microservices",
  "Monolith",
  "Architecture",
  "Design",
  "Pattern",
  "Singleton",
  "Factory",
  "Observer",
  "Strategy",
  "Adapter",
  "Decorator",
  "Facade",
  "Proxy",
  "Command",
  "Iterator",
  "Prototype",
  "Template",
  "State",
  "Memento",
  "Visitor",
  "Interpreter",
  "Mediator",
  "Chain",
  "Responsibility",
  "Flyweight",
  "Builder",
  "Bridge",
  "Composite",
  "Proxy",
  "Facade",
  "Observer",
  "Strategy",
  "Adapter",
  "Decorator",
  "Command",
  "Iterator",
  "Prototype",
  "Template",
  "State",
  "Memento",
  "Visitor",
  "Interpreter",
  "Mediator",
  "Chain",
  "Responsibility",
  "Flyweight",
  "Builder",
  "Bridge",
  "Composite",
];
